apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb-producer
  name: bb-producer
  namespace: myns
spec:
  volumes:
    - name: data-vol
      emptyDir: {}          
  containers:
  - image: busybox
    name: bb-producer
    command: ["/bin/sh"]
    args: ["-c", "while true; do  dt=$(shuf -i 0-100000 -n 1); echo $(date):= Hello > /var/log/top-${dt}.txt ; sleep 5;done"]
    volumeMounts:
      - mountPath: /var/log
        name: data-vol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
